name: Deploy
on:
  push:
    branches: [ test_deploy ]

jobs:
  run-on-ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: s-weigand/setup-conda@v1
      - name: build
        run: |
          uname -a
          git fetch --tags
          conda config --set solver libmamba
          bash build.sh
      - name: save
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: |
            dist/*bz2
            dist/*dmg