name: Deploy
on:
  push:
    branches: [ test_deploy ]

jobs:
  run-on-ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          conda env list
  run-on-macos:
    name: Run on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          conda env list
