name: Deploy
on:
  push:
    branches: [ test_deploy ]

jobs:
  run-on-ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: s-weigand/setup-conda@v1
      - run: |
          set -vx
          uname -a
          git status
          git remote -v
          git fetch --tags
          git tag
          git branch -a
          git describe --tags --always --dirty
          conda env list
          conda config --set solver libmamba
#          conda install -y pyinstaller
#          echo $PATH
#          which pyinstaller
#          which pyi-makespec
          bash build.sh
          ls -lR
      - name: save
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: dist/Molpro
#  run-on-macos:
#    name: Run on macos
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: |
#          uname -a
#          git describe
#          conda env list
#          conda config --set solver libmamba
#          bash build.sh
#          ls -lR
