name: Deploy
on:
  push:
    branches: [ test_deploy ]
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, [macOS, ARM64]]
    steps:
      - uses: actions/checkout@v3
      - uses: s-weigand/setup-conda@v1
        if: ${{ matrix.os} == ubuntu-latest
      - name: Build
        run: |
          uname -a
          git fetch --tags
          conda config --set solver libmamba
          bash build.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          # name: ${{ matrix.os }}
          path: |
            dist/*bz2
            dist/*dmg