name: Deploy
on:
  push:
    branches: [ test_deploy ]

jobs:
  run-on-ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -vx
          uname -a
          git status
          git remote -v
          git fetch --tags
          git tag
          git describe --tags
          git describe
          conda env list
          conda config --set solver libmamba
          conda install -y -c conda-forge pyinstaller
          which pyinstaller
          echo $PATH
          which pyi-makespec
          bash build.sh
          ls -lR
  run-on-macos:
    name: Run on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          git describe
          conda env list
          conda config --set solver libmamba
          bash build.sh
          ls -lR
