name: Tag latest

on:
  push:
    branches:
      - 'master'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
#      - name: Tag commit
#        uses: tvdias/github-tagger@v0.0.1
#        with:
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#          tag: "latest-${{ steps.date.outputs.date }}"
      - name: Checkout branch "master"
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-${{ steps.date.outputs.date }}
          release_name: latest-${{ steps.date.outputs.date }}
#          draft: false
#          prerelease: false
  clean:
    name: Clean previous latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete old latest releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          #          repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 1
          #          keep_min_download_counts: 1 # Optional parameters
          #          delete_expired_data: 10 # Optional parameters
          delete_tag_pattern: '.*latest*' # defaults to ""
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}